-- AlterTable
ALTER TABLE "Bet" ALTER COLUMN "amountBet" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "status" SET DEFAULT 'PENDING',
ALTER COLUMN "amountWon" DROP NOT NULL,
ALTER COLUMN "amountWon" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Game" ALTER COLUMN "isFinished" SET DEFAULT false;

-- AlterTable
ALTER TABLE "Participants" ALTER COLUMN "balance" SET DEFAULT 0,
ALTER COLUMN "balance" SET DATA TYPE DOUBLE PRECISION;
